### ISSUE TITLE
unable to install via brew

### ISSUE THREAD

**Issue by lrehmann** [Proxmark/homebrew-proxmark3#11]
$ brew install proxmark3
==> Installing proxmark3 from proxmark/proxmark3
==> Downloading https://github.com/proxmark/proxmark3/archive/v2.3.0.tar.gz
Already downloaded: /Users/lukerehmann/Library/Caches/Homebrew/proxmark3-2.3.0.tar.gz
==> make clean
==> make all
Last 15 lines from /Users/lukerehmann/Library/Logs/Homebrew/proxmark3/02.make:
                 from /usr/local/Cellar/arm-none-eabi-gcc/20160926/arm-none-eabi/include/stdio.h:61,
                 from ../include/hitagS.h:13,
                 from apps.h:19,
                 from start.c:13:
/usr/local/Cellar/arm-none-eabi-gcc/20160926/arm-none-eabi/include/sys/_stdint.h:48:20: error: conflicting types for 'uint32_t'
 typedef __uint32_t uint32_t ;
                    ^
In file included from ../include/usb_cmd.h:21:0,
                 from ../include/proxmark3.h:17,
                 from start.c:12:
./stdint.h:21:24: note: previous declaration of 'uint32_t' was here
 typedef unsigned int   uint32_t;
                        ^
make[1]: *** [obj/start.o] Error 1
make: *** [armsrc/all] Error 2

**Comment by marshmellow42** [comment]
See #5 but then we have a new issue with current code #10 that will be worked on next.
