### ISSUE TITLE
Installation failed on MacOS Sierra 10.12.5

### ISSUE THREAD

**Issue by nuomi** [Proxmark/homebrew-proxmark3#12]
Hi,

I followed this tutorial trying to install Proxmark3 software on MacOS
https://github.com/Proxmark/proxmark3/wiki/MacOS

but failed on 'brew install proxmark3' 

Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (caskroom/cask).
No changes to formulae.

==> Installing proxmark3 from proxmark/proxmark3
==> Downloading https://github.com/proxmark/proxmark3/archive/v2.3.0.tar.gz
Already downloaded: /Users/nuomi/Library/Caches/Homebrew/proxmark3-2.3.0.tar.gz
==> make clean
==> make all
Last 15 lines from /Users/nuomi/Library/Logs/Homebrew/proxmark3/02.make:
                 from /usr/local/Cellar/arm-none-eabi-gcc/20150921/arm-none-eabi/include/stdio.h:48,
                 from ../include/hitagS.h:13,
                 from apps.h:19,
                 from start.c:13:
/usr/local/Cellar/arm-none-eabi-gcc/20150921/arm-none-eabi/include/sys/_stdint.h:32:20: error: conflicting types for 'uint32_t'
 typedef __uint32_t uint32_t ;
                    ^
In file included from ../include/usb_cmd.h:21:0,
                 from ../include/proxmark3.h:17,
                 from start.c:12:
./stdint.h:21:24: note: previous declaration of 'uint32_t' was here
 typedef unsigned int   uint32_t;
                        ^
make[1]: *** [obj/start.o] Error 1
make: *** [armsrc/all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/proxmark/homebrew-proxmark3/issues

any help?  thank you

**Comment by nuomi** [comment]
I also tried "brew install --HEAD proxmark3",  still no luck:

==> Installing proxmark3 from proxmark/proxmark3
==> Cloning https://github.com/proxmark/proxmark3.git
Cloning into '/Users/nuomi/Library/Caches/Homebrew/proxmark3--git'...
remote: Counting objects: 885, done.
remote: Compressing objects: 100% (659/659), done.
remote: Total 885 (delta 260), reused 616 (delta 219), pack-reused 0
Receiving objects: 100% (885/885), 14.53 MiB | 1.03 MiB/s, done.
Resolving deltas: 100% (260/260), done.
Checking out files: 100% (943/943), done.
==> Checking out branch master
==> make clean
==> make all
Last 15 lines from /Users/nuomi/Library/Logs/Homebrew/proxmark3/02.make:
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_USE_MACOSX    -c -o lua.o lua.c
gcc -o lua   lua.o liblua.a -lm -lreadline
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_USE_MACOSX    -c -o luac.o luac.c
gcc -o luac   luac.o liblua.a -lm -lreadline
gcc -MT obj/proxmark3.o -MMD -MP -MF obj/proxmark3.Td -std=c99 -D_ISOC99_SOURCE -I. -I../include -I../common -I../zlib -I/opt/local/include -I../liblua -Wall  -g -O3 -DHAVE_GUI -DZ_SOLO -DZ_PREFIX -DNO_GZIP -DZLIB_PM3_TUNED  -c -o obj/proxmark3.o proxmark3.c
mv -f obj/proxmark3.Td obj/proxmark3.d
gcc -MT obj/uart.o -MMD -MP -MF obj/uart.Td -std=c99 -D_ISOC99_SOURCE -I. -I../include -I../common -I../zlib -I/opt/local/include -I../liblua -Wall  -g -O3 -DHAVE_GUI -DZ_SOLO -DZ_PREFIX -DNO_GZIP -DZLIB_PM3_TUNED  -c -o obj/uart.o uart.c
mv -f obj/uart.Td obj/uart.d
gcc -MT obj/util.o -MMD -MP -MF obj/util.Td -std=c99 -D_ISOC99_SOURCE -I. -I../include -I../common -I../zlib -I/opt/local/include -I../liblua -Wall  -g -O3 -DHAVE_GUI -DZ_SOLO -DZ_PREFIX -DNO_GZIP -DZLIB_PM3_TUNED  -c -o obj/util.o util.c
util.c:670:17: error: use of undeclared identifier '_SC_NPROCESSORS_ONLN'
        return sysconf(_SC_NPROCESSORS_ONLN);
                       ^
1 error generated.
make[1]: *** [obj/util.o] Error 1
make: *** [client/all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/proxmark/homebrew-proxmark3/issues

**Comment by marshmellow42** [comment]
You have to use HEAD for now, but then yes there is an issue #10 that is working on the second error.

**Comment by pwpiwi** [comment]
Pushed a possible fix. Please try with --HEAD and give us a feedback (none of the maintainers uses MacOS).

**Comment by iceman1001** [comment]
time to close?

**Comment by nuomi** [comment]
Yeah it works, like a charm. You guys rocks, thank you.

==> Installing proxmark3 from proxmark/proxmark3
==> Cloning https://github.com/proxmark/proxmark3.git
Updating /Users/nuomi/Library/Caches/Homebrew/proxmark3--git
==> Checking out branch master
==> make clean
==> make all
==> Install success!  Only proxmark3-flasher (modern firmware) is available.
==> The latest bootloader and firmware binaries are ready and waiting in the current homebrew Cellar within s
🍺  /usr/local/Cellar/proxmark3/HEAD-eabbb16: 10 files, 1MB, built in 1 minute 45 seconds
