### ISSUE TITLE
Missing file in stable release

### ISSUE THREAD

**Issue by osbock** [Proxmark/homebrew-proxmark3#17]
MacOSX High Sierra 10.13.4
brew install proxmark3
==> Installing proxmark3 from proxmark/proxmark3
==> Downloading https://github.com/proxmark/proxmark3/archive/v3.0.1.tar.gz
Already downloaded: /Users/zua691/Library/Caches/Homebrew/proxmark3-3.0.1.tar.gz
==> make clean
==> make all
Error: No such file or directory - client/emv/capk.txt

brew install --HEAD proxmark3 works

**Comment by iceman1001** [comment]
Thanks for noticing,  this will be resolved once we make a new release.  Until then --HEAD is the way to go.

**Comment by pwpiwi** [comment]
@osbock: I have pushed a fix. Please try again.

**Comment by osbock** [comment]
I have verified this fixed. Tested both release and --HEAD on MacOS High Sierra 10.13.4
