### ISSUE TITLE
Proxmark3 HEAD install issue (Brew)

### ISSUE THREAD

**Issue by jinjirosan** [Proxmark/homebrew-proxmark3#8]
I'm on MacOS Sierra 10.12.4, installed latest Xcode and Homebrew.

brew install -HEAD proxmark3

==> Installing proxmark3 from proxmark/proxmark3
==> Downloading https://github.com/proxmark/proxmark3/archive/v2.3.0.tar.gz
Already downloaded: /Users/jinjirosan/Library/Caches/Homebrew/proxmark3-2.3.0.tar.gz
==> make clean
==> make all
Last 15 lines from /Users/jinjirosan/Library/Logs/Homebrew/proxmark3/02.make:
                 from /usr/local/Cellar/arm-none-eabi-gcc/20160926/arm-none-eabi/include/stdio.h:61,
                 from ../include/hitagS.h:13,
                 from apps.h:19,
                 from start.c:13:
/usr/local/Cellar/arm-none-eabi-gcc/20160926/arm-none-eabi/include/sys/_stdint.h:48:20: error: conflicting types for 'uint32_t'
 typedef __uint32_t uint32_t ;
                    ^
In file included from ../include/usb_cmd.h:21:0,
                 from ../include/proxmark3.h:17,
                 from start.c:12:
./stdint.h:21:24: note: previous declaration of 'uint32_t' was here
 typedef unsigned int   uint32_t;
                        ^
make[1]: *** [obj/start.o] Error 1
make: *** [armsrc/all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/proxmark/homebrew-proxmark3/issues

**Comment by pwpiwi** [comment]
Try `--HEAD` instead of `-HEAD`

**Comment by jinjirosan** [comment]
Ah yes, had multiple tries last night. Couldnt see straight :)
I've ran it with --HEAD, had to fix qt5 links which now seem to work but this is the new output:

brew install --HEAD proxmark3
==> Installing proxmark3 from proxmark/proxmark3
==> Cloning https://github.com/proxmark/proxmark3.git
Updating /Users/jinjirosan/Library/Caches/Homebrew/proxmark3--git
==> Checking out branch master
==> make clean
==> make all
Last 15 lines from /Users/jinjirosan/Library/Logs/Homebrew/proxmark3/02.make:
    T loadAcquire() const Q_DECL_NOTHROW { return Ops::loadAcquire(_q_value); }
                                                                   ^
/usr/local/Cellar/qt/5.8.0_2/include/QtCore/qbasicatomic.h:106:52: error: use of undeclared identifier 'Ops'
    void storeRelease(T newValue) Q_DECL_NOTHROW { Ops::storeRelease(_q_value, newValue); }
                                                   ^
/usr/local/Cellar/qt/5.8.0_2/include/QtCore/qbasicatomic.h:106:70: error: use of undeclared identifier '_q_value'
    void storeRelease(T newValue) Q_DECL_NOTHROW { Ops::storeRelease(_q_value, newValue); }
                                                                     ^
/usr/local/Cellar/qt/5.8.0_2/include/QtCore/qbasicatomic.h:110:86: error: use of undeclared identifier 'Ops'
    static Q_DECL_CONSTEXPR bool isReferenceCountingNative() Q_DECL_NOTHROW { return Ops::isReferenceCountingNative(); }
                                                                                     ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[1]: *** [obj/proxgui.o] Error 1
make: *** [client/all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/proxmark/homebrew-proxmark3/issues

These open issues may also help:
Proxmark3 HEAD install issue (Brew) https://github.com/Proxmark/homebrew-proxmark3/issues/8

**Comment by pwpiwi** [comment]
Can you please post the complete content of /Users/jinjirosan/Library/Logs/Homebrew/proxmark3/02.make ?

**Comment by jinjirosan** [comment]
Edit: apologies, can't seem to get it pasted correctly. Dropped the file here now.
[02.make.txt](https://github.com/Proxmark/homebrew-proxmark3/files/907332/02.make.txt)

Thx for your quick responses, I really appreciate your help.

**Comment by pwpiwi** [comment]
Excellent. Thanks for your feedback. I have made some changes to the Makefile and made a Pull Request in Proxmark/proxmark3. Are you able to test this?

**Comment by jinjirosan** [comment]
Absolutely. Just to be sure, I run "brew tap proxmark/proxmark3" again and then install with --HEAD

This gives the following result (full 02.make file attached below):

Atlas:github jinjirosan$ brew tap Proxmark/proxmark3
Atlas:github jinjirosan$ brew install --HEAD proxmark3
==> Installing proxmark3 from proxmark/proxmark3
==> Cloning https://github.com/proxmark/proxmark3.git
Updating /Users/jinjirosan/Library/Caches/Homebrew/proxmark3--git
==> Checking out branch master
==> make clean
==> make all
Last 15 lines from /Users/jinjirosan/Library/Logs/Homebrew/proxmark3/02.make:
    T loadAcquire() const Q_DECL_NOTHROW { return Ops::loadAcquire(_q_value); }
                                                                   ^
/usr/local/Cellar/qt/5.8.0_2/include/QtCore/qbasicatomic.h:106:52: error: use of undeclared identifier 'Ops'
    void storeRelease(T newValue) Q_DECL_NOTHROW { Ops::storeRelease(_q_value, newValue); }
                                                   ^
/usr/local/Cellar/qt/5.8.0_2/include/QtCore/qbasicatomic.h:106:70: error: use of undeclared identifier '_q_value'
    void storeRelease(T newValue) Q_DECL_NOTHROW { Ops::storeRelease(_q_value, newValue); }
                                                                     ^
/usr/local/Cellar/qt/5.8.0_2/include/QtCore/qbasicatomic.h:110:86: error: use of undeclared identifier 'Ops'
    static Q_DECL_CONSTEXPR bool isReferenceCountingNative() Q_DECL_NOTHROW { return Ops::isReferenceCountingNative(); }
                                                                                     ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[1]: *** [obj/proxgui.o] Error 1
make: *** [client/all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/proxmark/homebrew-proxmark3/issues

These open issues may also help:
Proxmark3 HEAD install issue (Brew) https://github.com/Proxmark/homebrew-proxmark3/issues/8
Atlas:github jinjirosan$

[02.make-1641.txt](https://github.com/Proxmark/homebrew-proxmark3/files/907515/02.make-1641.txt)

**Comment by jinjirosan** [comment]
I'm not too proficient in git and homebrew so bear with me here. 
I've found /Users/jinjirosan/Library/Caches/Homebrew and under proxmark3--git/client/ changed the contents of the two files of your pull request. It did give the same result so unsure if I did this right.

**Comment by pwpiwi** [comment]
Let's wait for the other maintainers to review the code. Once it is committed you can easily test with the same brew command...

**Comment by darker0n** [comment]
so i have the same problem on Sierra

**Comment by pwpiwi** [comment]
Changes have been committed to master. Please try `brew install --HEAD proxmark3` again and post the results.

**Comment by jinjirosan** [comment]
Nice it works, thx for your effort and quick actions!

Here's the output:

Atlas:~ jinjirosan$ brew install --HEAD proxmark3
==> Installing proxmark3 from proxmark/proxmark3
==> Cloning https://github.com/proxmark/proxmark3.git
Updating /Users/jinjirosan/Library/Caches/Homebrew/proxmark3--git
==> Checking out branch master
==> make clean
==> make all
==> Install success!  Only proxmark3-flasher (modern firmware) is available.
==> The latest bootloader and firmware binaries are ready and waiting in the current homebrew Cellar within share/firmware.
🍺  /usr/local/Cellar/proxmark3/HEAD-8aee1b8: 10 files, 988.9KB, built in 41 seconds
Atlas:~ jinjirosan$ proxmark3
syntax: proxmark3 <port>

	Linux example:'proxmark3 /dev/ttyACM0'

help:   proxmark3 -h

	Dump all interactive help at once
markdown:   proxmark3 -m

	Dump all interactive help at once in markdown syntax
Atlas:~ jinjirosan$
